VocAsk/VocAsk/urls.py
from django.contrib import admin
from main import views
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("datenschutz/", views.datenschutz),
    path("impressum/", views.impressum),
    path("about/", views.about, name="about"),
    path("anleitung/", views.anleitung),
    path("accounts/", include("accounts.urls")),
    path("abfrage/", include("interrogations.urls")),
]

VocAsk/accounts/urls.py
from django.urls import path
from accounts import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup_view, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]

VocAsk/accounts/models.py
# from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class VocabularySets(models.Model):
    title = models.CharField(max_length=45)
    vocEn = models.TextField()
    vocDe = models.TextField()
    user = models.ForeignKey(User, unique=False, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

VocAsk/accounts/forms.py
from django import forms
from .models import VocabularySets


class SubmitVocabularySets(forms.ModelForm):
    class Meta:
        model = VocabularySets
        fields = "__all__"

VocAsk/accounts/views.py
"""
Django views for accounts app.

"""
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


def signup_view(request):
    """
    Display a User creation form that logs User in after creation.

    **Context**

    ``form``
        An instance of: `UserCreationForm`.

    ``user``
        User credentials.

    **Template**

    :template:`accounts/signup.html`
    :template:`main/static/templates/index.html`

    """
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # log user in
            login(request, user)
            return redirect("index")
    else:
        form = UserCreationForm()
    return render(request, "accounts/signup.html", {"form": form})


def login_view(request):
    """
    Display an authentication form for users to log in.

    **Context**

    ``form``
        An instance of: `AuthenticationForm`.

    ``user``
        User credentials.

    **Template**

    :template:`accounts/login.html`
    :template:`main/static/templates/index.html`

    """
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log user in
            user = form.get_user()
            login(request, user)
            return redirect("index")
    else:
        form = AuthenticationForm()
    return render(request, "accounts/login.html", {"form": form})


def logout_view(request):
    """
    Log users out.

    **Template**

    :template:`main/static/templates/index.html`

    """
    if request.method == "POST":
        logout(request)
        return redirect("index")

VocAsk/accounts/templates/accounts/login.html
{% extends 'base-layout.html' %}

{% block content %}
<div class="center-div">
    <div class="standard-box">
        <div class="center-div">
            <form class="access-form" action="{% url 'accounts:login' %}" method="post">
                <div class="center-div">
                    <h2 class="access-h">Log in</h2>
                </div>
                {% csrf_token %}
                {{form}}
                <input type="submit" class="inside-box-button form-button" value="Login">
            </form>
        </div>
    </div>
</div>
{% endblock %}

VocAsk/accounts/templates/accounts/signup.html
{% extends 'base-layout.html' %}

{% block content %}
<div class="center-div">
    <div class="standard-box">
        <div class="center-div">
            <form class="access-form" action="/accounts/signup/" method="post">
                <div class="center-div">
                    <h2 class="access-h">Signup</h2>
                </div>
                {% csrf_token %}
                {{form}}
                <input class="inside-box-button form-button" type="submit" value="Signup">
            </form>
        </div>
    </div>
</div>

{% endblock %}